"""
gRPC streaming inference server.

Handles concurrent Generate RPCs by submitting InferenceRequests to the
engine and streaming back one token per response message. Each RPC is an
asyncio coroutine that awaits a per-request token queue; the engine loop
pushes tokens into queues as they are generated.

Usage:
    python -m src.server.grpc_server \
        --model meta-llama/Llama-2-7b-hf \
        --port 50051 \
        --gpu-memory-utilization 0.90
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import signal
import sys
import time
import uuid
from concurrent import futures
from typing import AsyncIterator, Dict, Optional

import grpc
from grpc import aio as grpc_aio

# Proto-generated stubs (generated by: python -m grpc_tools.protoc ...)
# We import conditionally so the module is importable even before proto codegen.
try:
    from . import inference_pb2 as pb2                    # type: ignore
    from . import inference_pb2_grpc as pb2_grpc          # type: ignore
    _PROTO_AVAILABLE = True
except ImportError:
    _PROTO_AVAILABLE = False

from ..engine.engine import InferenceEngine
from ..engine.request import InferenceRequest, RequestStatus, SamplingParams
from ..model.config import CacheConfig, ModelConfig, SchedulerConfig, ServerConfig

logger = logging.getLogger(__name__)

ENGINE_VERSION = "0.1.0"


# ── Token queue ──────────────────────────────────────────────────────────────

class TokenQueue:
    """One asyncio queue per active RPC. The engine pushes (token_id, text, finished) tuples."""

    def __init__(self) -> None:
        self._q: asyncio.Queue = asyncio.Queue()

    async def get(self):
        return await self._q.get()

    def put_nowait(self, item) -> None:
        self._q.put_nowait(item)


# ── Servicer ─────────────────────────────────────────────────────────────────

class InferenceServicer:
    def __init__(self, engine: InferenceEngine, tokenizer) -> None:
        self.engine = engine
        self.tokenizer = tokenizer
        self._queues: Dict[str, TokenQueue] = {}

        # Register callback so the engine can push tokens to RPC streams
        self.engine.register_token_callback(self._on_token)

    def _on_token(
        self, request_id: str, token_id: int, finished: bool, finish_reason: str
    ) -> None:
        q = self._queues.get(request_id)
        if q is None:
            return
        try:
            token_text = self.tokenizer.decode([token_id], skip_special_tokens=False)
        except Exception:
            token_text = ""
        q.put_nowait((token_id, token_text, finished, finish_reason))

    async def Generate(self, request, context) -> AsyncIterator:
        if not _PROTO_AVAILABLE:
            await context.abort(grpc.StatusCode.UNIMPLEMENTED, "Proto stubs not generated")
            return

        request_id = request.request_id or str(uuid.uuid4())
        sp = request.sampling
        sampling_params = SamplingParams(
            temperature=sp.temperature if sp.temperature > 0 else 1.0,
            top_p=sp.top_p if sp.top_p > 0 else 1.0,
            top_k=sp.top_k if sp.top_k > 0 else -1,
            max_tokens=sp.max_tokens if sp.max_tokens > 0 else 512,
            min_tokens=sp.min_tokens if sp.min_tokens > 0 else 1,
            stop_sequences=list(sp.stop_sequences),
        )

        try:
            prompt_token_ids = self.tokenizer.encode(request.prompt)
        except Exception as e:
            await context.abort(grpc.StatusCode.INVALID_ARGUMENT, f"Tokenization failed: {e}")
            return

        q = TokenQueue()
        self._queues[request_id] = q

        inf_request = InferenceRequest(
            prompt=request.prompt,
            prompt_token_ids=prompt_token_ids,
            sampling_params=sampling_params,
            request_id=request_id,
        )
        self.engine.add_request(inf_request)

        prompt_tokens = len(prompt_token_ids)
        completion_tokens = 0
        start_time = time.monotonic()
        ttft_ms: Optional[float] = None

        try:
            while True:
                if await context.is_active() is False:
                    self.engine.abort_request(request_id)
                    break

                token_id, token_text, finished, finish_reason = await asyncio.wait_for(
                    q.get(), timeout=60.0
                )
                completion_tokens += 1
                if ttft_ms is None:
                    ttft_ms = (time.monotonic() - start_time) * 1000

                fr_enum = {
                    "stop": pb2.FINISH_REASON_STOP,
                    "length": pb2.FINISH_REASON_LENGTH,
                    "aborted": pb2.FINISH_REASON_ABORTED,
                }.get(finish_reason, pb2.FINISH_REASON_UNSPECIFIED)

                usage = None
                if finished:
                    e2e_ms = (time.monotonic() - start_time) * 1000
                    usage = pb2.UsageStats(
                        prompt_tokens=prompt_tokens,
                        completion_tokens=completion_tokens,
                        ttft_ms=ttft_ms or 0.0,
                        e2e_latency_ms=e2e_ms,
                    )

                yield pb2.GenerateResponse(
                    request_id=request_id,
                    token_text=token_text,
                    token_id=token_id,
                    finished=finished,
                    finish_reason=fr_enum,
                    usage=usage,
                )

                if finished:
                    break

        except asyncio.TimeoutError:
            logger.warning("Request %s timed out waiting for token", request_id[:8])
            self.engine.abort_request(request_id)
        finally:
            self._queues.pop(request_id, None)

    async def Cancel(self, request, context):
        self.engine.abort_request(request.request_id)
        return pb2.CancelResponse(success=True)

    async def Health(self, request, context):
        stats = self.engine.get_stats()
        return pb2.HealthResponse(
            healthy=True,
            num_waiting_reqs=stats.get("waiting", 0),
            num_running_reqs=stats.get("running", 0),
            num_free_blocks=stats.get("free_blocks", 0),
            engine_version=ENGINE_VERSION,
        )


# ── Server entrypoint ────────────────────────────────────────────────────────

async def serve(args: argparse.Namespace) -> None:
    logging.basicConfig(
        level=getattr(logging, args.log_level.upper(), logging.INFO),
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    model_config = ModelConfig(
        model_name_or_path=args.model,
        dtype=args.dtype,
    )
    cache_config = CacheConfig(
        block_size=args.block_size,
        gpu_memory_utilization=args.gpu_memory_utilization,
        swap_space_gb=args.swap_space,
    )
    scheduler_config = SchedulerConfig(
        max_num_seqs=args.max_num_seqs,
        max_num_batched_tokens=args.max_num_batched_tokens,
    )
    server_config = ServerConfig(
        host=args.host,
        port=args.port,
        max_workers=args.max_workers,
    )

    logger.info("Loading model %s ...", args.model)
    engine = InferenceEngine(
        model_config=model_config,
        cache_config=cache_config,
        scheduler_config=scheduler_config,
    )
    await engine.start()
    logger.info("Engine ready.")

    from transformers import AutoTokenizer
    tokenizer = AutoTokenizer.from_pretrained(args.model)

    servicer = InferenceServicer(engine, tokenizer)

    grpc_server = grpc_aio.server(
        options=[
            ("grpc.max_send_message_length", 64 * 1024 * 1024),
            ("grpc.max_receive_message_length", 64 * 1024 * 1024),
        ]
    )
    if _PROTO_AVAILABLE:
        pb2_grpc.add_InferenceServiceServicer_to_server(servicer, grpc_server)

    listen_addr = f"{server_config.host}:{server_config.port}"
    grpc_server.add_insecure_port(listen_addr)
    await grpc_server.start()
    logger.info("gRPC server listening on %s", listen_addr)

    loop = asyncio.get_running_loop()
    stop_event = asyncio.Event()

    def _shutdown(sig, _):
        logger.info("Received %s, shutting down...", signal.Signals(sig).name)
        loop.call_soon_threadsafe(stop_event.set)

    for sig in (signal.SIGINT, signal.SIGTERM):
        signal.signal(sig, _shutdown)

    await stop_event.wait()
    await grpc_server.stop(grace=5)
    await engine.stop()
    logger.info("Shutdown complete.")


def main() -> None:
    parser = argparse.ArgumentParser(description="LLM Inference Engine gRPC Server")
    parser.add_argument("--model", required=True, help="HuggingFace model name or local path")
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=50051)
    parser.add_argument("--dtype", default="float16", choices=["float16", "bfloat16"])
    parser.add_argument("--block-size", type=int, default=16, choices=[8, 16, 32])
    parser.add_argument("--gpu-memory-utilization", type=float, default=0.90)
    parser.add_argument("--swap-space", type=float, default=4.0,
                        help="CPU swap space in GiB")
    parser.add_argument("--max-num-seqs", type=int, default=256)
    parser.add_argument("--max-num-batched-tokens", type=int, default=4096)
    parser.add_argument("--max-workers", type=int, default=16)
    parser.add_argument("--log-level", default="INFO")
    args = parser.parse_args()

    asyncio.run(serve(args))


if __name__ == "__main__":
    main()
